### ISSUE TITLE
Add a license, license headers, contribution guidelines and code of conduct

### ISSUE THREAD

**Issue by filmaj** [adobe/xdm4registry#1]
Please add these files as all Adobe open source projects require them. You can copy them from github.com/adobe/starter-repo.

If you are not sure what this stuff means or have questions about them, then please fill the form out at opensource.corp.adobe.com and us at Adobe's Open Source Office will help guide you through it.

Note that these files - especially the license - must be in place _before_ open sourcing.

**Comment by jwen-adobe** [comment]
@filmaj License, license headers, contribution guidelines and code of conduct are all added.
